### ISSUE TITLE
Issue for Opening link of U-Net and Swin UNETR

### ISSUE THREAD

**Issue by zihao12Lian** [MrGiovanni/AbdomenAtlas#10]
Dear author,

Appreciate your work. Could you please update the link for pre-trainted model of U-Net 
and Swin UNETR? I cannot open it because links are not exsisted.

Best,
zihao

**Comment by zihao12Lian** [comment]
I tried to use the instruction you provided to download the two pre-trained checkpoints, but I opened those .pth format and they are indeed html format, which means files in drobox are deleted. 

cd pretrained_weights/
wget https://www.dropbox.com/s/po2zvqylwr0fuek/swin_unetr.base_5000ep_f48_lr2e-4_pretrained.pt
wget https://www.dropbox.com/s/lh5kuyjxwjsxjpl/Genesis_Chest_CT.pt
cd ../
cd pretrained_checkpoints/
wget https://www.dropbox.com/s/jdsodw2vemsy8sz/swinunetr.pth
wget https://www.dropbox.com/s/lyunaue0wwhmv5w/unet.pth
cd ..

![image](https://github.com/user-attachments/assets/8a2965a9-a13a-42a4-b3e9-ffe0e41878be)
![image](https://github.com/user-attachments/assets/d46490d2-f781-4ac2-b4b8-d5d52e979af5)

**Comment by Mentholatum** [comment]
@zihao12Lian I encountered the same issue; it seems the author of the [CLIP-Driven-Universal-Model](https://github.com/ljwztc/CLIP-Driven-Universal-Model) accidentally removed the corresponding project.
You can try this [link](https://www.dropbox.com/scl/fi/fhtbwxfrw5yahz50ladtc/clip_driven_universal_model.pth?rlkey=tq4nnfdtrv7dn1wv7qy1peox2&st=fuepxd0m&dl=0). But I'm not sure which backbone network's weights these are. If you know, please feel free to let me know.

**Comment by MrGiovanni** [comment]
Hi @Mentholatum and @zihao12Lian 

Thanks for letting us know. The previous links were inactive. You can find all the weights from here:
https://github.com/MrGiovanni/SuPreM?tab=readme-ov-file#a-suite-of-pre-trained-models-suprem


Best,
Zongwei
