### ISSUE TITLE
About nnUnet pre-trained model

### ISSUE THREAD

**Issue by Betty-J** [MrGiovanni/AbdomenAtlas#3]
Hi, Thanks for sharing! I noticed that you provided two pre-trained models for download. So regarding nnUnet, will pre-training models be provided? I saw in your article that you used three models including nnUnet.

**Comment by Chongyu1117** [comment]
In the "Implementation Details" section of Appendix A, it is mentioned that *nnU-Net is trained on 47 CT volumes from the BTCV dataset*. For those interested in replicating the training process, the BTCV dataset can be downloaded, and the weights can be trained independently. Alternatively, the nnU-Net GitHub repository offers the convenience of downloading pre-trained weights specifically for the BTCV dataset. Please be aware that the pretrained weights from nnU-Net v1 are not compatible with the latest version, V2. Unfortunately, pretrained weights options are not yet available for V2. I recommend following the structure with nnU-Net v1 you can run 
```bash
nnUNet_download_pretrained_model Task017_AbdominalOrganSegmentation 
```
To download the pretained weights on BTCV
