### ISSUE TITLE
Dataset Release 

### ISSUE THREAD

**Issue by tushaarkataria** [MrGiovanni/AbdomenAtlas#6]
Are you going to release the datasets or do we have to run the code to obtain the annotations ? I am a little confused. You have mentioned in FAQ that ~5000 volume annotation will be release but i don't see any link where i can download.

**Comment by MrGiovanni** [comment]
Hello @tushaarkataria 

Thanks for your question. We have made detailed annotations for 5,195 CT volumes available. The announcement can be found at
https://github.com/MrGiovanni/AbdomenAtlas/issues/2#issuecomment-1780201579

We are working with other dataset contributors to obtain permission to re-distribute their CT volumes. As of now, you will have to download CT volumes from each individual website. This situation will be improved soon, as we aim to release the whole package, including data and annotations, in the near future!

Thanks,

Zongwei
