### ISSUE TITLE
Composition of the dataset

### ISSUE THREAD

**Issue by Ideal-Bushgorman** [MrGiovanni/AbdomenAtlas#7]
Hi ! Thank you for your awesome work. Could you please to disclose the composition of the dataset, as it intersects with many public datasets and may require consideration of the source of the data when using it

**Comment by MrGiovanni** [comment]
Dear @Devil-Ideal 

The source of the data was summarized in Table 3 of our paper (https://www.cs.jhu.edu/~alanlab/Pubs23/qu2023abdomenatlas.pdf).

We recognized the importance of data source information for transparency. We are preparing the ID mapping between our BDMAP_XXXX and their original dataset IDs. It will be released soon.

Thanks,
Zongwei

**Comment by Ideal-Bushgorman** [comment]
> Dear @Devil-Ideal
> 
> The source of the data was summarized in Table 3 of our paper (https://www.cs.jhu.edu/~alanlab/Pubs23/qu2023abdomenatlas.pdf).
> 
> We recognized the importance of data source information for transparency. We are preparing the ID mapping between our BDMAP_XXXX and their original dataset IDs. It will be released soon.
> 
> Thanks, Zongwei

 Sorry, I must have been too careless. Thank you !
