### ISSUE TITLE
Is this dataset a combination of existing public datasets? If so, could you provide a list of referenced datasets?

### ISSUE THREAD

**Issue by xia-my** [MrGiovanni/AbdomenAtlas#8]
Is this dataset a combination of existing public datasets? If so, could you provide a list of referenced datasets?

**Comment by MrGiovanni** [comment]
Hi @xia-my 

The list of public datasets included in AbdomenAtlas 1.0 has been reported in our paper - Table 3: The information for an assembly of datasets.
https://www.cs.jhu.edu/~alanlab/Pubs23/qu2023abdomenatlas.pdf

Best,
Zongwei
